### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by Sir-Will** [sdslabs/jinora#10]
if there is a new design it would be great to have a login screen too insteaed of the popup box.

**Comment by captn3m0** [comment]
True. I'd looked at lightweight dialog boxes earlier, but couldn't find anything worth using.
But since the new design uses polymer, I might be able to find something better.

**Comment by gauravgrover95** [comment]
Why not use a modal? There are tons of modal plugins available there. I am dropping a link to example below: 

http://codepen.io/sol0mka/full/XJjLxe/

**Comment by apsdehal** [comment]
@gauravgrover95 This was a one day hack and made in a hurry and is supposed to be maintained by community as well as SDSLabs as per need. Why not make a pull request instead and contribute to codebase?
Also if you have a look at the comment above jinora uses polymer so you might want to look into it.

**Comment by gauravgrover95** [comment]
Thanks for the reply and its really appreciable that it was made in a single day.

**Comment by karandesai-96** [comment]
Safe to close.
