### ISSUE TITLE
Ban common/admin Username

### ISSUE THREAD

**Issue by apsdehal** [sdslabs/jinora#16]
Common user name that include admin/sdslabs as substring should be banned.

**Comment by captn3m0** [comment]
I had seen a gist somewhere with a list of such usernames or subdomains. Will look for it.

**Comment by captn3m0** [comment]
Found more than one.

https://gist.github.com/caseyohara/1453705

https://gist.github.com/mahemoff/2314663

https://gist.github.com/SoHiggo/93b306fad56d9ddfc998

**Comment by captn3m0** [comment]
@sdslabs/members You should first take a look at this. This is a far easier issue than real bans.
