### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/jinora#2]
We are working on a redesign for the v2. The first design was based on slate/slate by @tj, but we are doing a proper design for v2.

Here's the latest mockup:

![ch67-01](https://cloud.githubusercontent.com/assets/584253/5773054/e1dd31e0-9d82-11e4-8911-2882dbff555d.png)

@aviral125 is taking care of this.

**Comment by aviral125** [comment]
![ch68-01](https://cloud.githubusercontent.com/assets/10558579/5773133/c249f858-9d83-11e4-91b6-749e4da4c3fa.png)

**Comment by captn3m0** [comment]
Fix the timestamp colors
Ditch the topbar, its too sdslabs specific.

**Comment by aviral125** [comment]
![ch70-01](https://cloud.githubusercontent.com/assets/10558579/5773264/14da7bf4-9d86-11e4-88e8-dea083151a40.png)

**Comment by aviral125** [comment]
![ch71-01](https://cloud.githubusercontent.com/assets/10558579/5773271/3b56bb26-9d86-11e4-888a-3619855ab1d4.png)

**Comment by aviral125** [comment]
top bar removed
second one message bar size is changed

**Comment by aviral125** [comment]
time stamps changed as well

**Comment by captn3m0** [comment]
Members -> "Online Members"

**Comment by captn3m0** [comment]
Sorry about the hasty design, but I decided to try polymer. Its deployed. Lets keep this ticket open for any improvements.

**Comment by aviral125** [comment]
![j1_flat](https://cloud.githubusercontent.com/assets/10558579/6831415/3467fc26-d346-11e4-8b42-d344d63cde35.png)

**Comment by abhshkdz** [comment]
1. Spacing in general looks great
2. Grays look too light to me
3. 'Members online' list needs more work, see Dribbble for inspiration
4. The profile images aren't vertically center aligned, even the text. shouldn't they be?

**Comment by captn3m0** [comment]
1. I like this in general
2. I need a way to mark *confidential* messages
3. I'll probably keep "chat with sdslabs" at top as title
4. Should we show usernames or full names? I'm inclined towards usernames. This would go for both places (message and online view)

**Comment by aviral125** [comment]
1. I will prefer username over full name
2. The icon on top right is for DM(confidential messages)

**Comment by aviral125** [comment]
![comparison_flat](https://cloud.githubusercontent.com/assets/10558579/6840603/9d110974-d3a1-11e4-8951-e45bab5a2312.png)
To distinguish  between lab members and general public I have come up with three ideas: 
1. Coloured rectangle on the left.(first one) 
2. Gradient rectangle(second one) 
3. SDSlabs golden star(last one) 
which one is better

**Comment by captn3m0** [comment]
Definitely not 3, because jinora is used by more teams than just us.

I don't like the other two options either because they are not clear immediately.

I'd prefer a generic admin badge for every chat message, maybe as an overlay on the userimage orwhere the golden badge is.

**Comment by aviral125** [comment]
For admin badge can we use golden sherif badge(and team's logo on it if it exists)?

**Comment by captn3m0** [comment]
Sheriff badge- yes
team logo - no

**Comment by aviral125** [comment]
So should we go with the sherif badge?

**Comment by aviral125** [comment]
Which one is better? 
![comparison_badge-02](https://cloud.githubusercontent.com/assets/10558579/6840828/f83d899a-d3a5-11e4-84ef-9c37ec5eda7a.png)

**Comment by captn3m0** [comment]
I had a different sheriff badge in mind. The second one comes closes, but can be improved. Try something with a rounded star, like real badges?

The first one looks like a dog-ribbon, btw :poodle:

**Comment by aviral125** [comment]
something like converse logo?

**Comment by captn3m0** [comment]
Link please

**Comment by aviral125** [comment]
http://www.zastavki.com/pictures/originals/2013/Brands_Converse_logo_in_black_background_046349_.png

**Comment by captn3m0** [comment]
Yeah. Something like that

**Comment by aviral125** [comment]
![comparison_badge_2-02](https://cloud.githubusercontent.com/assets/10558579/6841221/a84bfe38-d3ac-11e4-9af2-dfc8ea93e614.png)

**Comment by aviral125** [comment]
![1_flat](https://cloud.githubusercontent.com/assets/10558579/6844411/7b4e89a8-d3d1-11e4-84f1-19eee5e65045.png)
With improved badges and spacing.

**Comment by captn3m0** [comment]
@chettyarun thoughts on spacing?

**Comment by chettyarun** [comment]
Typo still feels weird to me. Titles especially. And the left chat messages doesn't look like messages to me. Don't know why.

**Comment by aviral125** [comment]
![2_flat](https://cloud.githubusercontent.com/assets/10558579/6846359/798bde56-d3e3-11e4-87e7-d08aa8eae195.png)
With improved spacing

**Comment by captn3m0** [comment]
Please change everything to usernames. I also need a connected/disconnected status somewhere.

Can you add a link in the announcement and style it as well?

**Comment by aviral125** [comment]
1. There is a coloured ring around the user's photo(top right) which tells about the status(two colours red and green , its red in mockup)
2. Why do we need a link in the announcement and whats there to style

**Comment by captn3m0** [comment]
1. I'd also like green borders around chat messages from people who are online.
2. The connected ring looks fine
3. We will often give out links to current contests or perhaps jinora instructions. basically i want to know how a link would look in the announcement

**Comment by aviral125** [comment]
1. The grey tick is for people who online(lab members for now),do we still need green borders
2. The links will be displayed the same way they are displayed in Facebook,just the start and the end

**Comment by captn3m0** [comment]
1. What if a team member sent a message and then went offline. We need indicators for both, no?
2. I want to _see_ how a link would look. Not read a description. More specifically: alignment, color, underlines, italics, font etc

**Comment by aviral125** [comment]
![3_flat](https://cloud.githubusercontent.com/assets/10558579/6851080/d65e93ca-d402-11e4-8dc6-7494cb252f02.png)
Green ticks are for online members and the red are for offline ones

**Comment by captn3m0** [comment]
Nopes, bad UI.

These are _complementary_, which means that they should refer to opposites. However, one of them means: admin+online. And another means admin+offline, which are not opposites.

We need two indicators. I'd recommend trying out the green ring on online images for showing status and the sheriff badge for all admin messages.

**Comment by aviral125** [comment]
Does the link look fine?

**Comment by captn3m0** [comment]
It feels out of place in its current color. Also, I'd like a version with an inline link, instead of one so conveniently placed at end.

**Comment by aviral125** [comment]
1. colour of the link is changed
2. I have used different three badges 
3. Coloured rings are around team member's image
![4_flat](https://cloud.githubusercontent.com/assets/10558579/6852040/7fa8813e-d408-11e4-801e-c9e73fff893d.png)

**Comment by captn3m0** [comment]
Can you please use cats to make it clearer who is admin and who's not.

- The grey dot is not good
- I don't think there is any point in red rings. If you are online, you get a green ring. If you are not, no ring.
- We can't have cool link text, like the one you used since we will be using /topic in slack to make announcements. So, you will have to put in the whole link.

**Comment by aviral125** [comment]
![5_flat](https://cloud.githubusercontent.com/assets/10558579/6852305/ea3cf308-d409-11e4-9a4f-4e34d3b37856.png)
People with badges are admins others are not(faster than putting cats photos)
Do we need to display full link

**Comment by captn3m0** [comment]
- Can you try a thicker green ring?
- The topic is gonna be something like "Please refrain from posting answers on chat. Visit https://backdoor.sdslabs.co/about before doing a writeup", and not just a link.

**Comment by aviral125** [comment]
which badge are we going with(1,2,3 are different)
![6_flat](https://cloud.githubusercontent.com/assets/10558579/6853432/2d94b1de-d411-11e4-9676-3d21ac54b523.png)

**Comment by captn3m0** [comment]
Third one looks best. (5 pointed white filled).

Also, its Announcement (not plural).

Shift to usernames when you get time.

Rest all looks good to me. @sdslabs/members does anyone else have any thoughts on this?
