### ISSUE TITLE
Ban Users

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/jinora#21]
I think the right way to address this is to hellban users. This is the discussion I spotted yesterday on chat:

![image](https://cloud.githubusercontent.com/assets/584253/10409862/3505437a-6f4d-11e5-81db-4d385af70d0c.png)

1. Keep user sessions
2. Ban sessions

Banned users are delegated to #public-hell channel, where only hellbanned users are talking. Moderators can have the public-hell channel muted and just check it occasionally to make sure banning is not too aggressive. Their messages don't reach anyone else other than that channel. You can unban users if they are not spamming any more, but this is the general idea.

See https://en.wikipedia.org/wiki/Stealth_banning

**Comment by captn3m0** [comment]
@sdslabs/members Anyone working on this?

**Comment by divijbindlish** [comment]
@tnmy44: Seeing that you fixed a (minor) bug in jinora before, want to take this up?

**Comment by abhikandoi2000** [comment]
Isn't @nightfury already on it?

On Tuesday 13 October 2015, Divij Bindlish <notifications@github.com> wrote:

> @tnmy44 <https://github.com/tnmy44>: Seeing that you fixed a (minor) bug
> in jinora before, want to take this up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdslabs/jinora/issues/21#issuecomment-147533867>.
>


-- 
Abhishek Kandoi
Third Year, Computer Science and Engineering
Indian Institute of Technology Roorkee
About Me : about.me/kandoiabhi
GitHub: github.com/abhikandoi2000

**Comment by apsdehal** [comment]
Yes, he is.

**Comment by arpit270896** [comment]
Yes, I am.

**Comment by shagunsodhani** [comment]
Yes, you are.

**Comment by abhikandoi2000** [comment]
Now we know he is.

On Tuesday 13 October 2015, Shagun Sodhani <notifications@github.com> wrote:

> Yes, you are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sdslabs/jinora/issues/21#issuecomment-147621316>.
>


-- 
Abhishek Kandoi
Third Year, Computer Science and Engineering
Indian Institute of Technology Roorkee
About Me : about.me/kandoiabhi
GitHub: github.com/abhikandoi2000

**Comment by captn3m0** [comment]
Isn't this already merged and done with? Can we close this issue?
