### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by divijbindlish** [sdslabs/jinora#22]
Should we include translation in Jinora? Can we think of a good way to implement this (since this is a common chat platform)? Or is it too much effort?
![screenshot from 2015-10-14 22 13 52](https://cloud.githubusercontent.com/assets/3282643/10490843/e4993bfe-72c0-11e5-9c88-1ab3441c2b55.png)

**Comment by captn3m0** [comment]
Too much effort. Lets do one thing (public chat) and do it well.

**Comment by aryanraj** [comment]
I was also thinking of the same.
