### ISSUE TITLE
RTM Integration

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/jinora#3]
Slack released an RTM API recently (Real Time Messaging), which can be used to add the following features to Jinora:

- List of slack members online on `#public`
- Joining/Leaving notifications for slack members

**Comment by captn3m0** [comment]
This is now integrated.

**Comment by abhikandoi2000** [comment]
:thumbsup:

On Wed, Mar 18, 2015 at 9:05 PM, Abhay Rana <notifications@github.com>
wrote:

> This is now integrated.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sdslabs/jinora/issues/3#issuecomment-83023056>.
>



-- 
Abhishek Kandoi
Third Year, Computer Science and Engineering
Indian Institute of Technology Roorkee
About Me : about.me/kandoiabhi
GitHub: github.com/abhikandoi2000
