### ISSUE TITLE
Safari: no messages are displayed

### ISSUE THREAD

**Issue by caske33** [sdslabs/jinora#32]
On safari, no messages are displayed. In the console, the error "TypeError: template.async is not a function. (In 'template.async','template.async' is undefined) on polymer.js:36

Might be related to #12.

As experienced by @OlivierKamers.

**Comment by OlivierKamers** [comment]
Another error message on Safari:
`TypeError: undefined is not an object (evaluating '$("#announcement-area")[0].style')`on polymer.js:103
However the chat seems to be working now.
