### ISSUE TITLE
Parse Integration

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/jinora#4]
Currently, jinora only stores the last 100 messages in memory using a circular buffer. We are planning to improve it, by shifting the data store to Parse.com

- Store complete logs in parse as well as Slack
- Allow viewing of older logs via parse
- Storing the announcement in Parse as well (although I might use the Slack API and use the channel purpose/topic instead, which would be comparatively easier)
- Maybe even add full text search using parse?

**Comment by ravikishore1993** [comment]
Other alternatives:

- Firebase
- Remotestorage
- gundb

**Comment by captn3m0** [comment]
I've increased the buffer size, and as such I don't think this is needed.

Announcements can be stored in slack topics.
