### ISSUE TITLE
Customize the title of landing page

### ISSUE THREAD

**Issue by pravj** [sdslabs/jinora#5]
Hi,

The *title* there is [hardcoded](https://github.com/sdslabs/jinora/blob/master/index.html#L4), so it ends up showing `chat with SDSLabs` for all the instances.

Probably, the environment variable `TEAM_DOMAIN` can be used to customize it for others.

*Jinora* is awesome. :zap:

**Comment by captn3m0** [comment]
Thanks for filing.

Its hard to get capitalization right, so maybe go with another configuration option?

**Comment by pravj** [comment]
Yeah!
Another thing to support your argument is that, we have a team named, `nkman-test` and the `TEAM_DOMAIN` for that is `nkmantest`. No underscore.
