### ISSUE TITLE
Notifications on new messages

### ISSUE THREAD

**Issue by pravj** [sdslabs/jinora#6]
In the current version, when users are on other tabs, they don't get any notification for a new message in jinora.

This can be solved by having a handler to update the page title in such a way, that it shows count of unread messages.
![Tab-Notification](http://www.adweek.com/socialtimes/files/2010/08/tab-counter.jpg?red=af)

Currently, `chat:msg` events are [being used](https://github.com/sdslabs/jinora/blob/master/public/app.js#L55-59) to append a new message element in the DOM.
The same event can be used for this, with the help of a variable counting unread messages. 

State of the tab can be used in this. Updating that variable to 0 when the tab is active and increasing it by 1, in case the tab is not active and there is any `chat:msg` event.

**Comment by captn3m0** [comment]
@anumarathore Want to work on this?

**Comment by anumarathore** [comment]
ok

**Comment by SirWilli** [comment]
Or something like this ;)
![image](https://cloud.githubusercontent.com/assets/5961995/6727656/f5ae671c-ce23-11e4-8e33-27a6f3caf917.png)

**Comment by captn3m0** [comment]
Two libraries that do this:

- http://blog.tommoor.com/tinycon/
- http://lab.ejci.net/favico.js/

**Comment by apsdehal** [comment]
Other thing to do would be desktop notifications.
