### ISSUE TITLE
Send button not working

### ISSUE THREAD

**Issue by SirWilli** [sdslabs/jinora#9]

**Comment by captn3m0** [comment]
I assume this is on the new interface. Can you specify which browser?

I'm guessing my keycode detection is wrong. But does clicking on the button work?

**Comment by SirWilli** [comment]
I'm useing Opera.

Enter works to send the message, I mean the button at the bottom right corner. If I click on it it doesn't send the message.

**Comment by captn3m0** [comment]
Thanks, I'll look into it.
